export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCES = "REGISTER_SUCCES"
export const REGISTER_FAILURE = "REGISTER_FAILURE"


export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCES = "LOGIN_SUCCES"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGIN_TWO_STEP_REQUEST = "LOGIN_TWO_STEP_REQUEST"
export const LOGIN_TWO_STEP_SUCCES = "LOGIN_TWO_STEP_SUCCES"
export const LOGIN_TWP_STEP_FAILURE = "LOGIN_TWP_STEP_FAILURE"


export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCES = "GET_USER_SUCCES"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const SEND_VERIFICATION_REQUEST = "SEND_VERIFICATION__REQUEST"
export const SEND_VERIFICATION_SUCCES = "SEND_VERIFICATION_SUCCES"
export const SEND_VERIFICATION_FAILURE = "SEND_VERIFICATION_FAILURE"

export const ENABLE_TWO_STEP_AUTHENTICATION_REQUEST = "ENABLE_TWO_STEP_AUTHENTICATION_REQUEST"
export const ENABLE_TWO_STEP_AUTHENTICATION_SUCCES = "ENABLE_TWO_STEP_AUTHENTICATION_SUCCES"
export const ENABLE_TWO_STEP_AUTHENTICATION_FAILURE = "ENABLE_TWO_STEP_AUTHENTICATION_FAILURE"


export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST"
export const VERIFY_OTP_SUCCES = "VERIFY_OTP_SUCCES"
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE"
