// Action types for Withdrawal
export const WITHDRAWAL_REQUEST = 'WITHDRAWAL_REQUEST';
export const WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS';
export const WITHDRAWAL_FAILURE = 'WITHDRAWAL_FAILURE';

// Action types for Withdrawal Proceed
export const WITHDRAWAL_PROCEED_REQUEST = 'WITHDRAWAL_PROCEED_REQUEST';
export const WITHDRAWAL_PROCEED_SUCCESS = 'WITHDRAWAL_PROCEED_SUCCESS';
export const WITHDRAWAL_PROCEED_FAILURE = 'WITHDRAWAL_PROCEED_FAILURE';

// Action types for Get Withdrawal History
export const GET_WITHDRAWAL_HISTORY_REQUEST = 'GET_WITHDRAWAL_HISTORY_REQUEST';
export const GET_WITHDRAWAL_HISTORY_SUCCESS = 'GET_WITHDRAWAL_HISTORY_SUCCESS';
export const GET_WITHDRAWAL_HISTORY_FAILURE = 'GET_WITHDRAWAL_HISTORY_FAILURE';



// Action types for Add Payment Details
export const ADD_PAYMENT_DETAILS_REQUEST = 'ADD_PAYMENT_DETAILS_REQUEST';
export const ADD_PAYMENT_DETAILS_SUCCESS = 'ADD_PAYMENT_DETAILS_SUCCESS';
export const ADD_PAYMENT_DETAILS_FAILURE = 'ADD_PAYMENT_DETAILS_FAILURE';

// Action types for Get Payment Details
export const GET_PAYMENT_DETAILS_REQUEST = 'GET_PAYMENT_DETAILS_REQUEST';
export const GET_PAYMENT_DETAILS_SUCCESS = 'GET_PAYMENT_DETAILS_SUCCESS';
export const GET_PAYMENT_DETAILS_FAILURE = 'GET_PAYMENT_DETAILS_FAILURE';
